### ISSUE TITLE
Cannot create instance from the server.json template

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/cookbook-keboola-generic-server#1]
16:50:45 
UTC-0800	CREATE_FAILED	
AWS::EC2::Instance	
Ec2Instance	
Non-Windows instances with a virtualization type of 'hvm' are currently not supported for this instance type.

(https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks?stackId=arn:aws:cloudformation:us-east-1:147946154733:stack%2Fdocker-demo%2F51f37f00-9b87-11e4-bc97-500162a66cb4&tab=events&filter=active)

**Comment by ondrejhlavacek** [comment]
tak jsem zkusil t1.micro a m1.small, to nejde, ale c3.large prošlo

**Comment by Halama** [comment]
jo c3.large a m3.medium je odladeny

**Comment by Halama** [comment]
pro ty ostatni to fixnu, m1.small uz je ale stary
