### ISSUE TITLE
Generic server starts with a key I can't use to log in

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/cookbook-keboola-generic-server#2]
Tried users root, ec2-user and deploy

**Comment by ondrejhlavacek** [comment]
#3 should fix it

**Comment by Halama** [comment]
tohle neni potreba stahuje to klice nas vsech z s3, normalne se tam prihlasis jako ec2-user

**Comment by ondrejhlavacek** [comment]
No nešlo mi to, zkoušel jsem to... Zejtra ti to nahraju :-)

**Comment by Halama** [comment]
je potreba pockat az se to nahodi. Pokud by to nefungovalo tak sem nesshcknes na jediny nas server :)

**Comment by ondrejhlavacek** [comment]
No narozený to bylo, cloudformation hlásil success, nebo mám čekat ještě
pak dal?

**Comment by Halama** [comment]
ne jakmile je success tak je to ok. Mám ale takovej pocit že když se to zkouší předtím tak to nějak jakoby blokneš.

**Comment by Halama** [comment]
to zkus jeste jednou

**Comment by ondrejhlavacek** [comment]
Čekal jsem na success a nic nedělal

**Comment by Halama** [comment]
docker-demo-01.keboola.com se dostanes?

**Comment by ondrejhlavacek** [comment]
a zkusil jsem vytvořit novej a taky to prošlo. hm. :-/ se tam muselo něco
drbnout, tak pardon za prudu!

On Tue, Jan 13, 2015 at 11:35 PM, Ondřej Hlaváček <
ondrej.hlavacek@keboola.com> wrote:

> jo, dostanu... divnost, velebnosti!
>
>
> On Tue, Jan 13, 2015 at 10:38 PM, Martin Halamíček <
> notifications@github.com> wrote:
>
>> docker-demo-01.keboola.com se dostanes?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/keboola/cookbook-keboola-generic-server/issues/2#issuecomment-69875336>
>> .
>>
>
>
>
> --
> Ondrej Hlavacek
> Developer, Keboola
> +1 (778) 551 2270
> @keboola
>



-- 
Ondrej Hlavacek
Developer, Keboola
+1 (778) 551 2270
@keboola

**Comment by ondrejhlavacek** [comment]
jo, dostanu... divnost, velebnosti!


On Tue, Jan 13, 2015 at 10:38 PM, Martin Halamíček <notifications@github.com
> wrote:

> docker-demo-01.keboola.com se dostanes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keboola/cookbook-keboola-generic-server/issues/2#issuecomment-69875336>
> .
>



-- 
Ondrej Hlavacek
Developer, Keboola
+1 (778) 551 2270
@keboola

**Comment by Halama** [comment]
jeste to prozkoumam, je to divny. Kdyby se tam neco drblo tak to nebude zeleny. Mam ale tu zkusenost ze kdyz se netrpelive snazim tam prihlasovat tak to pak nejak nejde a zabere to kdyz zadam treba primo ip adresu verejnou nebo fixni :)

**Comment by ondrejhlavacek** [comment]
Sel jsem přes hostname... Asi to dal nezkoumej, to by byla ztráta času, to
pak zas někdy zkusím

**Comment by Halama** [comment]
ok no kdyztak kdyz nejde hostname tak zkusit nekterou z IP. vetsinou s tim ale problem nemam pokud pockam na SUCCESS
